language: cpp

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      addons:
        apt:
          packages:
            - libxtst-dev
            - qtdeclarative5-dev
            - libavahi-compat-libdnssd-dev
      script: sh -x ./clean_build.sh

    - os: osx
      osx_image: xcode9
      script:
        - export COLUMNS=80
        - curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        - chmod +x ./macports-ci
        - ./macports-ci install
        - PATH="$PATH:/opt/local/bin"
        - sudo port -N install qt5-qtbase openssl
        - sh -x ./clean_build.sh

    - os: osx
      osx_image: xcode9
      script:
        - brew update
        - brew install qt openssl
        - sh -x ./clean_build.sh

install: true
