name: barrier-kvm # the Barrier Snappy for Linux / not tested on MAC yet
base: core18 
version: master
version-script: git -C parts/barrier/src/ describe --tags --long | sed "s/^v//"
summary: Eliminate the barrier between your machines.
description: |
       Barrier is KVM software forked from Symless's synergy 1.9 codebase. 
       Synergy was a commercialized reimplementation of the original 
       CosmoSynergy written by Chris Schoeneman.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  barrier-kvm:
    command: desktop-launch barrier #first run might take longer
    plugs: &plugs
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - wayland
      - x11

parts:
  desktop:
    plugin: nil
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5  
  qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git    
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all    
  barrier-kvm:
    source: https://github.com/payomagic/barrier.git
    plugin: cmake
    build-packages:
      - g++
      - gcc
      - make
      - xorg-dev 
      - libcurl4-openssl-dev
      - libavahi-compat-libdnssd-dev
      - libssl-dev
      - libx11-dev
      - libqt4-dev
      - qtbase5-dev
      - qt5-style-plugins
      - qt5ct
    stage-packages:
      - libxinerama-dev
      - libxinerama1
      - libxrandr-dev
      - libxrandr2
      - libxrender-dev
      - libxrender1
      - libxtst-dev
      - qtdeclarative5-dev
      - libavahi-compat-libdnssd-dev
      - libqt5gui5
      - libavahi-common-dev
      - libqt5x11extras5
      - libqt5svg5
      - libqt5svg5-dev
      - qt5ct
    after: [desktop-qt5]
