name: barrier-kvm # the Barrier Snappy for Linux / not tested on MAC yet
base: core18 
version: master
version-script: git -C parts/barrier/src/ describe --tags --long | sed "s/^v//"
summary: Eliminate the barrier between your machines.
description: |
       Barrier is KVM software forked from Symless's synergy 1.9 codebase. 
       Synergy was a commercialized reimplementation of the original 
       CosmoSynergy written by Chris Schoeneman.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  barrier:
    command: desktop-launch barrier #first run might take longer
    desktop: usr/share/applications/barrier.desktop
    plugs: &plugs
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - wayland
      - x11
  barrierc:
    command: desktop-launch barrierc
    plugs: *plugs
  barriers:
    command: desktop-launch barriers
    plugs: *plugs

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make

  barrier:
    source: .
    plugin: cmake
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - xorg-dev 
      - libcurl4-openssl-dev
      - libavahi-compat-libdnssd-dev
      - libssl-dev
      - libx11-dev
      - qtbase5-dev
      - qt5-style-plugins
      - libxinerama-dev
      - libxrandr-dev
      - libxrender-dev
      - libxtst-dev
      - qtdeclarative5-dev
      - libavahi-common-dev
      - libqt5svg5-dev
    stage-packages:
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libqt5gui5
      - libqt5x11extras5
      - libqt5svg5
      - libxtst6
      - libavahi-client3
      - libavahi-common3
      - libavahi-compat-libdnssd1
    after: [desktop-qt5]

  fix-icon:
    plugin: nil
    override-build:
      sed -i 's|Icon=barrier|Icon=/usr/share/icons/hicolor/scalable/apps/barrier.svg|' $SNAPCRAFT_STAGE/usr/share/applications/barrier.desktop
    after: [barrier]
